### ISSUE TITLE
GTFS fails to load when a route has zero trips

### ISSUE THREAD

**Issue by gt670dn** [OpenMetroMaps/OpenMetroMaps#5]
I tried to load the New York Subway GTFS, and loading crashed because the route "5X" has no trips in this file. 

This can be fixed by adding to org.openmetromaps.gtfs.GTFSImporter 
`if (longest == null) {
				continue;
			}`
in line 222 and
 `if (stopIds == null) {
				continue;
			}`
in line 297

**Comment by sebkur** [comment]
Cool, thanks for the report. Could you provide a link to the GTFS file for testing?

**Comment by gt670dn** [comment]
Of course, here via transitfeeds: https://transitfeeds.com/p/mta/79/latest/download

**Comment by sebkur** [comment]
I justed pushed 2ee78861 to fix this. Thanks!
