### ISSUE TITLE
GTFS Import fails because of unexpected Byte Order Mark

### ISSUE THREAD

**Issue by gt670dn** [OpenMetroMaps/OpenMetroMaps#6]
For Karlsruhe (https://transitfeeds.com/p/karlsruher-verkehrsverbundes/896/latest/download)
the GTFS File has a [Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark) at the start of each file. Because of that the import of this file is currently not possible.

**Comment by sebkur** [comment]
Do you have any idea whether it is common to have such a BOM in the GTFS files?
If it is, it will be surely useful to have support for this in the underlying [gtfs4j] library (https://github.com/OpenMetroMaps/gtfs4j) and could be easily implemented in [GtfsZip.java](https://github.com/OpenMetroMaps/gtfs4j/blob/master/csv-util/src/main/java/org/openmetromaps/gtfs4j/csv/GtfsZip.java) by wrapping all InputStreams with a [BOMInputStream](https://commons.apache.org/proper/commons-io/javadocs/api-release/org/apache/commons/io/input/BOMInputStream.html).
If it is not a common thing, I would consider writing a separate conversion tool instead that "fixes" a GTFS file by removing the BOMs before processing it with the importer.

**Comment by gt670dn** [comment]
Unfortunately I don't know if this is common. As for now I only encountered this problem with Karlsruhe.
But would implementing the BOMInputStream have any negative impact? If not, you could do it just to be safe.

**Comment by sebkur** [comment]
I just implemeted a workaround (2ff30a1a). It allows you to pass `--fix-boms` to the `gtfs-import` task
