### ISSUE TITLE
GTFS Converter writes comma as decimal separator for lat/lon values in output XML

### ISSUE THREAD

**Issue by gt670dn** [OpenMetroMaps/OpenMetroMaps#7]
My Locale is German on Win7, maybe this is the case why. The map-editor or viewer cannot open it because of the commas in the value.

**Comment by sebkur** [comment]
Does 140d11aa fix this for you?

**Comment by gt670dn** [comment]
Yes, it did! Thank you for fixing so fast.

**Comment by sebkur** [comment]
Thanks for the report!
